<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="14" passed="10" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-28T15:39:37 ICT" name="Suite1" finished-at="2023-11-28T15:39:37 ICT" duration-ms="431">
    <groups>
      <group name="myGroup">
        <method signature="testClass1.t1()[pri:0, instance:vn.DungVipPro.ktLab7.testClass1@4738a206]" name="t1" class="vn.DungVipPro.ktLab7.testClass1"/>
        <method signature="testClass1.t2()[pri:0, instance:vn.DungVipPro.ktLab7.testClass1@4738a206]" name="t2" class="vn.DungVipPro.ktLab7.testClass1"/>
        <method signature="testClass1.t3()[pri:0, instance:vn.DungVipPro.ktLab7.testClass1@4738a206]" name="t3" class="vn.DungVipPro.ktLab7.testClass1"/>
        <method signature="testClass3.d1()[pri:0, instance:vn.DungVipPro.ktLab7.testClass3@d86a6f]" name="d1" class="vn.DungVipPro.ktLab7.testClass3"/>
      </group> <!-- myGroup -->
    </groups>
    <test started-at="2023-11-28T15:39:37 ICT" name="suite1-test1" finished-at="2023-11-28T15:39:37 ICT" duration-ms="144">
      <class name="vn.DungVipPro.ktLab7.testClass2">
        <test-method signature="c1()[pri:0, instance:vn.DungVipPro.ktLab7.testClass2@bae7dc0]" started-at="2023-11-28T15:39:37 ICT" name="c1" finished-at="2023-11-28T15:39:37 ICT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c1 -->
        <test-method signature="c2()[pri:0, instance:vn.DungVipPro.ktLab7.testClass2@bae7dc0]" started-at="2023-11-28T15:39:37 ICT" name="c2" finished-at="2023-11-28T15:39:37 ICT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c2 -->
        <test-method signature="c3()[pri:0, instance:vn.DungVipPro.ktLab7.testClass2@bae7dc0]" started-at="2023-11-28T15:39:37 ICT" name="c3" finished-at="2023-11-28T15:39:37 ICT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c3 -->
        <test-method signature="c4()[pri:0, instance:vn.DungVipPro.ktLab7.testClass2@bae7dc0]" started-at="2023-11-28T15:39:37 ICT" name="c4" finished-at="2023-11-28T15:39:37 ICT" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at vn.DungVipPro.ktLab7.testClass2.c4(testClass2.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c4 -->
      </class> <!-- vn.DungVipPro.ktLab7.testClass2 -->
      <class name="vn.DungVipPro.ktLab7.testClass1">
        <test-method signature="t1()[pri:0, instance:vn.DungVipPro.ktLab7.testClass1@4738a206]" started-at="2023-11-28T15:39:37 ICT" name="t1" finished-at="2023-11-28T15:39:37 ICT" duration-ms="14" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at vn.DungVipPro.ktLab7.testClass1.t1(testClass1.java:10)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t1 -->
        <test-method signature="t2()[pri:0, instance:vn.DungVipPro.ktLab7.testClass1@4738a206]" started-at="2023-11-28T15:39:37 ICT" name="t2" finished-at="2023-11-28T15:39:37 ICT" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at vn.DungVipPro.ktLab7.testClass1.t2(testClass1.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t2 -->
        <test-method signature="t3()[pri:0, instance:vn.DungVipPro.ktLab7.testClass1@4738a206]" started-at="2023-11-28T15:39:37 ICT" name="t3" finished-at="2023-11-28T15:39:37 ICT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t3 -->
        <test-method signature="t4()[pri:0, instance:vn.DungVipPro.ktLab7.testClass1@4738a206]" started-at="2023-11-28T15:39:37 ICT" name="t4" finished-at="2023-11-28T15:39:37 ICT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t4 -->
        <test-method signature="t5(java.lang.String)[pri:0, instance:vn.DungVipPro.ktLab7.testClass1@4738a206]" started-at="2023-11-28T15:39:37 ICT" name="t5" data-provider="dp" finished-at="2023-11-28T15:39:37 ICT" duration-ms="7" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[one]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t5 -->
        <test-method signature="t5(java.lang.String)[pri:0, instance:vn.DungVipPro.ktLab7.testClass1@4738a206]" started-at="2023-11-28T15:39:37 ICT" name="t5" data-provider="dp" finished-at="2023-11-28T15:39:37 ICT" duration-ms="11" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[two]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t5 -->
      </class> <!-- vn.DungVipPro.ktLab7.testClass1 -->
    </test> <!-- suite1-test1 -->
    <test started-at="2023-11-28T15:39:37 ICT" name="suite-test2" finished-at="2023-11-28T15:39:37 ICT" duration-ms="74">
      <class name="vn.DungVipPro.ktLab7.testFactory">
        <test-method is-config="true" signature="f1()[pri:0, instance:vn.DungVipPro.ktLab7.testFactory@5ab956d7, instance params:[]]" started-at="2023-11-28T15:39:37 ICT" name="f1" test-instance-name="testFactory - Reports" finished-at="2023-11-28T15:39:37 ICT" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f1 -->
        <test-method signature="f()[pri:0, instance:vn.DungVipPro.ktLab7.testFactory@2892d68, instance params:[]]" started-at="2023-11-28T15:39:37 ICT" name="f" test-instance-name="testFactory - TestNG" finished-at="2023-11-28T15:39:37 ICT" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method is-config="true" signature="f2()[pri:0, instance:vn.DungVipPro.ktLab7.testFactory@5ab956d7, instance params:[]]" started-at="2023-11-28T15:39:37 ICT" name="f2" test-instance-name="testFactory - Reports" finished-at="2023-11-28T15:39:37 ICT" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f2 -->
        <test-method signature="f()[pri:0, instance:vn.DungVipPro.ktLab7.testFactory@5ab956d7, instance params:[]]" started-at="2023-11-28T15:39:37 ICT" name="f" test-instance-name="testFactory - Reports" finished-at="2023-11-28T15:39:37 ICT" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at vn.DungVipPro.ktLab7.testFactory.f(testFactory.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method is-config="true" signature="f2()[pri:0, instance:vn.DungVipPro.ktLab7.testFactory@5ab956d7, instance params:[]]" started-at="2023-11-28T15:39:37 ICT" name="f2" test-instance-name="testFactory - Reports" finished-at="2023-11-28T15:39:37 ICT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f2 -->
      </class> <!-- vn.DungVipPro.ktLab7.testFactory -->
      <class name="vn.DungVipPro.ktLab7.testClass3">
        <test-method signature="d1()[pri:0, instance:vn.DungVipPro.ktLab7.testClass3@d86a6f]" started-at="2023-11-28T15:39:37 ICT" name="d1" finished-at="2023-11-28T15:39:37 ICT" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- d1 -->
        <test-method signature="d2()[pri:0, instance:vn.DungVipPro.ktLab7.testClass3@d86a6f]" started-at="2023-11-28T15:39:37 ICT" name="d2" finished-at="2023-11-28T15:39:37 ICT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- d2 -->
      </class> <!-- vn.DungVipPro.ktLab7.testClass3 -->
    </test> <!-- suite-test2 -->
  </suite> <!-- Suite1 -->
</testng-results>
